{
 "title": "minectl",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(job)" } },
   { "name": "player", "query": { "query": "label_values(player)" } }
  ]
 },
 "panels": [
  {
   "title": "blocks mined",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_prometheus_exporter_blocks_mined_total{job=\"$server\", player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Walk On CM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_prometheus_exporter_walk_one_cm_total{job=\"$server\", player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Online",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "minecraft_prometheus_exporter_player_online_total{job=\"$server\"}"
    }
   ]
  },
  {
   "title": "💀",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_prometheus_exporter_deaths_total{job=\"$server\", player=\"$player\"}"
    }
   ]
  }
 ]
}