linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - typecheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - errcheck
    - gosec
    - goimports
    - nolintlint

linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: goCamel
        json: snake
