project_name: minectl
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        #- upx "{{ .Path }}"

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: [ "sign-blob", "-key=cosign.key", "-output=${signature}", "${artifact}" ]
    artifacts: checksum

dockers:
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}
docker_signs:
  - artifacts: all
    args: [ "sign", "-key=cosign.key", "${artifact}" ]
    stdin: '{{ .Env.COSIGN_PASSWORD }}'

brews:
  - tap:
      owner: dirien
      name: homebrew-dirien

    commit_author:
      name: dirien
      email: engin.diri@mail.schwarz

    folder: Formula
    homepage: "https://github.com/dirien/minectl"
    description: "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
    license: "Apache License 2.0"

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  extra_files:
    - glob: ./cosign.pub

nfpms:
  - file_name_template: "minectl-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/dirien/minectl
    description: "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
    maintainer: "Engin Diri engin.diri@mail.schwarz"
    license: "Apache License 2.0"
    vendor: minectl️️ Developers
    formats:
      - rpm
      - deb
      - apk
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999