project_name: minectl
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath


source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true

dockers:
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.description=minectl is a cli for creating Minecraft server on different cloud provider
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=io.artifacthub.package.maintainers=[{"name":"Engin Diri","email":"engin.diri@ediri.de"}]
      - --label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dirien/minectl/main/README.md
      - --label=io.artifacthub.package.logo-url=https://dirien.github.io/minectl/img/minectl-logo.png
      - --label=io.artifacthub.package.keywords=minecraft,server,cli
      - --label=io.artifacthub.package.license=Apache-2.0
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.description=minectl is a cli for creating Minecraft server on different cloud provider
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=io.artifacthub.package.maintainers=[{"name":"Engin Diri","email":"engin.diri@ediri.de"}]
      - --label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dirien/minectl/main/README.md
      - --label=io.artifacthub.package.logo-url=https://dirien.github.io/minectl/img/minectl-logo.png
      - --label=io.artifacthub.package.keywords=minecraft,server,cli
      - --label=io.artifacthub.package.license=Apache-2.0

docker_manifests:
  - name_template: 'ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}'
    image_templates:
      - 'ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/dirien/{{ .ProjectName }}:latest'
    image_templates:
      - 'ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64'


docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: manifests
    output: true
    args:
      - 'sign'
      - '${artifact}'

brews:
  - tap:
      owner: dirien
      name: homebrew-dirien

    commit_author:
      name: dirien
      email: engin.diri@mail.schwarz

    folder: Formula
    homepage: "https://github.com/dirien/minectl"
    description: "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
    license: "Apache License 2.0"

archives:
  - format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: "minectl-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/dirien/minectl
    description: "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
    maintainer: "Engin Diri engin.diri@mail.schwarz"
    license: "Apache License 2.0"
    vendor: minectl️️ Developers
    formats:
      - rpm
      - deb
      - apk
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
