project_name: minectl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}
  - image_templates: [ "ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64v8" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/dirien/{{ .ProjectName }}
docker_manifests:
  - name_template: ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/dirien/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/dirien/{{ .ProjectName }}:{{ .Version }}-arm64v8
brews:
  - tap:
      owner: dirien
      name: homebrew-dirien

    commit_author:
      name: dirien
      email: engin.diri@mail.schwarz

    folder: Formula

    homepage: "https://github.com/dirien/minectl"
    description: "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
    license: "Apache License 2.0"

archives:
  - format_overrides:
      - goos: windows
        format: zip
