apiVersion: minectl.ediri.io/v1alpha1
kind: MinecraftProxy
metadata:
  name: minecraft-proxy
spec:
  server:
    cloud: azure
    region: westeurope
    size: Standard_D2_v4
    ssh:
      port: 22
      keyFolder: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft"
      security: true
    port: 25577
  proxy:
    java:
      openjdk: 8
      xmx: 512M
      xms: 512M
      rcon:
        password: test
        port: 25575
        enabled: true
        broadcast: true
    type: waterfall
    version: 1.17-448
