apiVersion: ediri.io/minectl/v1alpha1
kind: MinecraftProxy
metadata:
  name: minecraft-proxy
spec:
  server:
    cloud: vultr
    region: fra
    size: "vc2-1c-1gb"
    ssh: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft"
    port: 25577
  proxy:
    java:
      openjdk: 8
      xmx: 512M
      xms: 512M
      rcon:
        password: test
        port: 25575
        enabled: true
        broadcast: true
    type: waterfall
    version: 1.17-448