apiVersion: ediri.io/minectl/v1alpha1
kind: MinecraftServer
metadata:
  name: minecraft-server-be
spec:
  server:
    cloud: do
    region: fra1
    size: s-4vcpu-8gb
    volumeSize: 100
    ssh: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft-be.pub"
  minecraft:
    edition: bedrock
    properties: |
      server-name=DigitalOcean Minecraft
      gamemode=survival
      force-gamemode=false
      difficulty=normal
      allow-cheats=false
      max-players=100
      online-mode=true
      white-list=false
      server-port=19132
      server-portv6=19133
      view-distance=32
      tick-distance=4
      player-idle-timeout=30
      max-threads=8
      level-name=Bedrock level
      level-seed=
      default-player-permission-level=member
      texturepack-required=false
      content-log-file-enabled=false
      compression-threshold=1
      server-authoritative-movement=server-auth
      player-movement-score-threshold=20
      player-movement-distance-threshold=0.3
      player-movement-duration-threshold-in-ms=500
      correct-player-movement=false
      server-authoritative-block-breaking=false
