apiVersion: minectl.ediri.io/v1alpha1
kind: MinecraftProxy
metadata:
  name: minecraft-proxy
spec:
  server:
    cloud: gce
    region: europe-west6-a
    size: e2-standard-2
    ssh:
      port: 22
      keyfolder: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft"
      fail2ban:
        bantime: 1000
        maxretry: 3
    port: 25577
  proxy:
    java:
      openjdk: 16
      xmx: 512M
      xms: 512M
    type: velocity
    version: 3.1.1-98