name: 'Publish minectl spec'
on:
  push:
    tags:
      - '*'
jobs:
  push-to-fig-autocomplete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate the spec
        run: go mod tidy && go run . generateFigSpec > minectl.ts

      - name: Create Autocomplete PR ## Create the autocomplete PR using this action
        uses: withfig/push-to-fig-autocomplete-action@74f26098865d70a99aaf2a449c705d7f9bec5ba3 # tag=v1.1.2
        with:
          token: ${{ secrets.GH_PAT }}
          autocomplete-spec-name: minectl
          spec-path: minectl.ts
          integration: cobra
